services:
  mysql-payment:
    image: mysql:latest
    restart: always
    container_name: mysql-payment
    hostname: "mysql-payment"
    environment:
      MYSQL_DATABASE: 'paymentdb'
      MYSQL_USER: 'paymentuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
      MSUSER_HOSTNAME: ms-user
      MSUSER_PORT: 8080
    ports:
      - '3310:3310'
    networks:
      - my_network


  mspayment:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-payment
    hostname: "ms-payment"
    environment:
      MYSQL_HOSTNAME: mysql-payment
      MYSQL_PORT: 3310
    ports:
      - 8084:8084
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true