services:
  mysql-payment:
    image: mysql:latest
    restart: always
    container_name: mysql-payment
    hostname: "mysql-payment"
    environment:
      MYSQL_DATABASE: 'paymentdb'
      MYSQL_USER: 'paymentuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
    ports:
      - '3309:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-payment" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - my_network


  mspayment:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-payment:
        condition: service_healthy
    hostname: "ms-payment"
    environment:
      MYSQL_HOSTNAME: mysql-payment
      MYSQL_PORT: 3309
      MSUSER_HOSTNAME: ms-user
      MSUSER_PORT: 8080
    ports:
      - 8083:8083
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true